USE master
IF DB_ID('VASKERIDB') IS NOT NULL
    BEGIN
        ALTER DATABASE VASKERIDB SET SINGLE_USER with ROLLBACK IMMEDIATE;
        DROP DATABASE VASKERIDB
    END

CREATE DATABASE VASKERIDB
GO
USE VASKERIDB
GO
DROP TABLE IF EXISTS USERS 

--CREATIING TABLE 1 - USER

CREATE TABLE USERS
    (ID int identity (1,1) NOT NULL,
    USERNAME NVARCHAR(255),
    EMAIL NVARCHAR(255) UNIQUE,
    PASSWRD NVARCHAR(255) CONSTRAINT PWD_CONSTRAINT CHECK (LEN(PASSWRD) >= 5) NOT NULL, 
    KONTO DECIMAL(15,2) ,
    VASKERI_ID INT ,
    DATEOFCREATION TIME,
    PRIMARY KEY (ID),
    
    )

--CREATIING TABLE 2 - VASKERI

CREATE TABLE VASKERI
    (ID int identity (1,1) NOT NULL,
    VASKERINAME NVARCHAR(255) NOT NULL,
    OPENING_TIME TIME,
    CLOSING_TIME TIME,   
    PRIMARY KEY (ID),
    CONSTRAINT USER_VASKERI FOREIGN KEY (ID) REFERENCES USERS(ID)
    )

--CREATIING TABLE 3 - MASKINE

CREATE TABLE MASKINE
    (ID int identity (1,1) NOT NULL,
    MASKINENAME NVARCHAR(255) NOT NULL,
    PRIS_VASK DECIMAL(8,2),
    VASK_DURATION_MINUTES INT, 
    VASKERI_ID INT,  
    PRIMARY KEY (ID),
    CONSTRAINT MASKINE_VASKERI FOREIGN KEY (ID) REFERENCES VASKERI(ID)
    )


--CREATIING TABLE 4 - BOOKING

CREATE TABLE BOOKING
    (ID int identity (1,1),
    BOOKING_TIME DATETIME,
    PRIMARY KEY (ID),
    USER_ID int FOREIGN KEY REFERENCES USERS(ID),
    MASKINE_ID INT FOREIGN KEY REFERENCES MASKINE(ID)
    )    
--INSERTING VALUES IN ALL THE TABLES
--USERS TABLE DATA INSERTION
INSERT INTO USERS (USERNAME ,EMAIL ,PASSWRD , KONTO  ,VASKERI_ID,DATEOFCREATION ) VALUES ('John','john_doe66@gmail.com','password',100.00,2,'2021-02-15')
INSERT INTO USERS (USERNAME ,EMAIL ,PASSWRD , KONTO  ,VASKERI_ID,DATEOFCREATION ) VALUES ('Niel Armstrong','firstman@nasa.gov','eagleLander69',1000.00,1,'20210210')
INSERT INTO USERS (USERNAME ,EMAIL ,PASSWRD , KONTO  ,VASKERI_ID,DATEOFCREATION ) VALUES ('Batman','noreply@thecave.com','Rob1n',500.00,3,'20200310')
INSERT INTO USERS (USERNAME ,EMAIL ,PASSWRD , KONTO  ,VASKERI_ID,DATEOFCREATION ) VALUES ('Goldman Sachs','moneylaundering@gs.com','NotRecognized',100000.00,1,'20210101')
INSERT INTO USERS (USERNAME ,EMAIL ,PASSWRD , KONTO  ,VASKERI_ID,DATEOFCREATION ) VALUES ('50 Cent','50cent@gmail.com','ItsMyBirthday',0.50,3,'20200706')

SELECT * FROM USERS

--VASKERI TABLE DATA INSERTION
INSERT INTO VASKERI (VASKERINAME,OPENING_TIME,CLOSING_TIME) VALUES ('Whitewash Inc.','0800','2000')
INSERT INTO VASKERI (VASKERINAME,OPENING_TIME,CLOSING_TIME) VALUES ('Double Bubble','0200','2200')
INSERT INTO VASKERI (VASKERINAME,OPENING_TIME,CLOSING_TIME) VALUES ('Wash & Coffee','1200','2000')

SELECT * FROM VASKERI

--MASKINE TABLE DATA INSERTION
INSERT INTO MASKINE (MASKINENAME,PRIS_VASK,VASK_DURATION_MINUTES,VASKERI_ID) VALUES ('Mielle 911 Turbo',5.00,60,2)
INSERT INTO MASKINE (MASKINENAME,PRIS_VASK,VASK_DURATION_MINUTES,VASKERI_ID) VALUES ('Siemens iClean',100.00,30,1)
INSERT INTO MASKINE (MASKINENAME,PRIS_VASK,VASK_DURATION_MINUTES,VASKERI_ID) VALUES ('Electrolax FX-2',15.00,45,2)

INSERT INTO MASKINE (MASKINENAME,PRIS_VASK,VASK_DURATION_MINUTES,VASKERI_ID) VALUES ('NASA Spacewasher 8000',500.00,5,1)
INSERT INTO MASKINE (MASKINENAME,PRIS_VASK,VASK_DURATION_MINUTES,VASKERI_ID) VALUES ('The Lost Sock',3.50,90,3)
INSERT INTO MASKINE (MASKINENAME,PRIS_VASK,VASK_DURATION_MINUTES,VASKERI_ID) VALUES ('Yo Mama',0.50,120,3)

SELECT * FROM MASKINE

--BOOKING TABLE DATA INSERTION
 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 12:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 1 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 1 )) 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 16:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 1 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 3 )) 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 08:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 2 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 4 )) 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 15:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 3 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 5 )) 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 20:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 4 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 2 )) 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 19:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 4 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 2 )) 

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 10:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 4 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 2 ))

INSERT INTO BOOKING( BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES( '2021-02-26 16:00:00', ( SELECT ID FROM USERS WHERE USERS.ID = 5 ), ( SELECT ID FROM MASKINE WHERE MASKINE.ID = 6 ))

SELECT * FROM BOOKING

--TRANSACTION 
  
BEGIN TRANSACTION  


INSERT INTO BOOKING(BOOKING_TIME,USER_ID,MASKINE_ID)
VALUES (GETDATE(),(SELECT ID FROM USERS WHERE USERS.ID = 4 ),
(SELECT MASKINE.ID FROM MASKINE WHERE MASKINE.ID =2))


COMMIT TRANSACTION  

SELECT * FROM BOOKING

--VIEW 

CREATE VIEW 
[BOOKING_VIEW] AS
SELECT BOOKING.BOOKING_TIME,USERS.USERNAME,MASKINE.MASKINENAME,MASKINE.PRIS_VASK
FROM BOOKING,USERS,MASKINE

SELECT * FROM [BOOKING_VIEW]


-- SELECT STATEMENTS
SELECT * FROM USERS WHERE USERS.EMAIL LIKE '%@gmail.com%'

SELECT * FROM MASKINE INNER JOIN BOOKING ON MASKINE.ID=BOOKING.MASKINE_ID

SELECT COUNT(BOOKING.ID) FROM BOOKING
 RIGHT JOIN MASKINE ON MASKINE.ID=BOOKING.MASKINE_ID GROUP BY MASKINE.ID

DELETE  FROM BOOKING WHERE cast(BOOKING_TIME as time) BETWEEN '12:00:00' AND '13:00:00'
SELECT * FROM BOOKING

UPDATE USERS
SET PASSWRD = 'SelinaKyle'
WHERE USERNAME = 'Batman';

SELECT * FROM USERS;

